/**
 * FH Technikum SmartCity IndoorNavigation API
 * This is an API for FH Technikum BWI16 SmartCity IndoorNavigationAPP
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wi15b099@technikum-wien.at
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client;

public class Pair {
  private String name = "";
  private String value = "";

  public Pair(String name, String value) {
    setName(name);
    setValue(value);
  }

  private void setName(String name) {
    if (!isValidString(name)) return;

    this.name = name;
  }

  private void setValue(String value) {
    if (!isValidString(value)) return;

    this.value = value;
  }

  public String getName() {
    return this.name;
  }

  public String getValue() {
    return this.value;
  }

  private boolean isValidString(String arg) {
    if (arg == null) return false;
    if (arg.trim().isEmpty()) return false;

    return true;
  }
}
