/**
 * FH Technikum SmartCity IndoorNavigation API
 * This is an API for FH Technikum BWI16 SmartCity IndoorNavigationAPP
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wi15b099@technikum-wien.at
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class AccessPoint {
  
  @SerializedName("mac")
  private String mac = null;
  @SerializedName("type")
  private Integer type = null;
  @SerializedName("activity")
  private Boolean activity = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getMac() {
    return mac;
  }
  public void setMac(String mac) {
    this.mac = mac;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getType() {
    return type;
  }
  public void setType(Integer type) {
    this.type = type;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getActivity() {
    return activity;
  }
  public void setActivity(Boolean activity) {
    this.activity = activity;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessPoint accessPoint = (AccessPoint) o;
    return (this.mac == null ? accessPoint.mac == null : this.mac.equals(accessPoint.mac)) &&
        (this.type == null ? accessPoint.type == null : this.type.equals(accessPoint.type)) &&
        (this.activity == null ? accessPoint.activity == null : this.activity.equals(accessPoint.activity));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.mac == null ? 0: this.mac.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.activity == null ? 0: this.activity.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessPoint {\n");
    
    sb.append("  mac: ").append(mac).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  activity: ").append(activity).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
