/**
 * FH Technikum SmartCity IndoorNavigation API
 * This is an API for FH Technikum BWI16 SmartCity IndoorNavigationAPP
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wi15b099@technikum-wien.at
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.AccessPoint;
import io.swagger.client.model.GridPoint;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GridAccessPoint {
  
  @SerializedName("signal")
  private Integer signal = null;
  @SerializedName("gridPoint")
  private GridPoint gridPoint = null;
  @SerializedName("accessPoint")
  private AccessPoint accessPoint = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getSignal() {
    return signal;
  }
  public void setSignal(Integer signal) {
    this.signal = signal;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public GridPoint getGridPoint() {
    return gridPoint;
  }
  public void setGridPoint(GridPoint gridPoint) {
    this.gridPoint = gridPoint;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public AccessPoint getAccessPoint() {
    return accessPoint;
  }
  public void setAccessPoint(AccessPoint accessPoint) {
    this.accessPoint = accessPoint;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GridAccessPoint gridAccessPoint = (GridAccessPoint) o;
    return (this.signal == null ? gridAccessPoint.signal == null : this.signal.equals(gridAccessPoint.signal)) &&
        (this.gridPoint == null ? gridAccessPoint.gridPoint == null : this.gridPoint.equals(gridAccessPoint.gridPoint)) &&
        (this.accessPoint == null ? gridAccessPoint.accessPoint == null : this.accessPoint.equals(gridAccessPoint.accessPoint));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.signal == null ? 0: this.signal.hashCode());
    result = 31 * result + (this.gridPoint == null ? 0: this.gridPoint.hashCode());
    result = 31 * result + (this.accessPoint == null ? 0: this.accessPoint.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GridAccessPoint {\n");
    
    sb.append("  signal: ").append(signal).append("\n");
    sb.append("  gridPoint: ").append(gridPoint).append("\n");
    sb.append("  accessPoint: ").append(accessPoint).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
