/**
 * FH Technikum SmartCity IndoorNavigation API
 * This is an API for FH Technikum BWI16 SmartCity IndoorNavigationAPP
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wi15b099@technikum-wien.at
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.GridPoint;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Stand {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("logo")
  private String logo = null;
  @SerializedName("GridPoint")
  private GridPoint gridPoint = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLogo() {
    return logo;
  }
  public void setLogo(String logo) {
    this.logo = logo;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public GridPoint getGridPoint() {
    return gridPoint;
  }
  public void setGridPoint(GridPoint gridPoint) {
    this.gridPoint = gridPoint;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Stand stand = (Stand) o;
    return (this.id == null ? stand.id == null : this.id.equals(stand.id)) &&
        (this.name == null ? stand.name == null : this.name.equals(stand.name)) &&
        (this.description == null ? stand.description == null : this.description.equals(stand.description)) &&
        (this.logo == null ? stand.logo == null : this.logo.equals(stand.logo)) &&
        (this.gridPoint == null ? stand.gridPoint == null : this.gridPoint.equals(stand.gridPoint));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.logo == null ? 0: this.logo.hashCode());
    result = 31 * result + (this.gridPoint == null ? 0: this.gridPoint.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Stand {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  logo: ").append(logo).append("\n");
    sb.append("  gridPoint: ").append(gridPoint).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
