/**
 * FH Technikum SmartCity IndoorNavigation API
 * This is an API for FH Technikum BWI16 SmartCity IndoorNavigationAPP
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wi15b099@technikum-wien.at
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.GridPoint;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Vector {
  
  @SerializedName("distance")
  private Integer distance = null;
  @SerializedName("startPoint")
  private GridPoint startPoint = null;
  @SerializedName("endPoint")
  private GridPoint endPoint = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getDistance() {
    return distance;
  }
  public void setDistance(Integer distance) {
    this.distance = distance;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public GridPoint getStartPoint() {
    return startPoint;
  }
  public void setStartPoint(GridPoint startPoint) {
    this.startPoint = startPoint;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public GridPoint getEndPoint() {
    return endPoint;
  }
  public void setEndPoint(GridPoint endPoint) {
    this.endPoint = endPoint;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Vector vector = (Vector) o;
    return (this.distance == null ? vector.distance == null : this.distance.equals(vector.distance)) &&
        (this.startPoint == null ? vector.startPoint == null : this.startPoint.equals(vector.startPoint)) &&
        (this.endPoint == null ? vector.endPoint == null : this.endPoint.equals(vector.endPoint));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.distance == null ? 0: this.distance.hashCode());
    result = 31 * result + (this.startPoint == null ? 0: this.startPoint.hashCode());
    result = 31 * result + (this.endPoint == null ? 0: this.endPoint.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Vector {\n");
    
    sb.append("  distance: ").append(distance).append("\n");
    sb.append("  startPoint: ").append(startPoint).append("\n");
    sb.append("  endPoint: ").append(endPoint).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
